"""add image_url and bio to users

Revision ID: 46621b669c9c
Revises: 63126e6f08b9
Create Date: 2026-05-30 18:52:37.424948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46621b669c9c'
down_revision = '63126e6f08b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
